export class doorlist {
    list = {
        "NextRealizeUrl": null,
        "Values": [
            {
                "Id": 1,
                "Customer": "Root",
                "Door": "Fire Department to PD",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 30,
                "OutZoneId": 31
            },
            {
                "Id": 2,
                "Customer": "Root",
                "Door": "Lobby door to PD",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 19,
                "OutZoneId": 26
            },
            {
                "Id": 3,
                "Customer": "Root",
                "Door": "Dispatch",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 32,
                "OutZoneId": 33
            },
            {
                "Id": 4,
                "Customer": "Root",
                "Door": "Hall door by Records",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 34,
                "OutZoneId": 26
            },
            {
                "Id": 5,
                "Customer": "Root",
                "Door": "SMVPDMDF",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 15,
                "OutZoneId": 28
            },
            {
                "Id": 7,
                "Customer": "Root",
                "Door": "Training Room Exit",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 19,
                "OutZoneId": 26
            },
            {
                "Id": 8,
                "Customer": "Root",
                "Door": "Kitchen Hallway EXIT",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 19,
                "OutZoneId": 26
            },
            {
                "Id": 9,
                "Customer": "Root",
                "Door": "Evidence Hallway Exit",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 19,
                "OutZoneId": 26
            },
            {
                "Id": 11,
                "Customer": "Root",
                "Door": "Jail Cells to Sally Port",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 20,
                "OutZoneId": 22
            },
            {
                "Id": 12,
                "Customer": "Root",
                "Door": "Sally Port to EXIT",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 20,
                "OutZoneId": 22
            },
            {
                "Id": 13,
                "Customer": "Root",
                "Door": "Jail Cell to Detective Wing",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 17,
                "OutZoneId": 25
            },
            {
                "Id": 14,
                "Customer": "Root",
                "Door": "Detective Wing to VA Lobby",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 17,
                "OutZoneId": 25
            },
            {
                "Id": 15,
                "Customer": "Root",
                "Door": "Detective's Hallway to EXIT",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "OpenNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 17,
                "OutZoneId": 25
            },
            {
                "Id": 16,
                "Customer": "Root",
                "Door": "Detective's Bull Pen to EXIT",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "OpenNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 16,
                "OutZoneId": 24
            },
            {
                "Id": 17,
                "Customer": "Root",
                "Door": "Gate Rear",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 39,
                "OutZoneId": 40
            },
            {
                "Id": 19,
                "Customer": "Root",
                "Door": "TOWER IDF3",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "OpenNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 14,
                "OutZoneId": 29
            },
            {
                "Id": 20,
                "Customer": "Root",
                "Door": "Narcotics",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 35,
                "OutZoneId": 36
            },
            {
                "Id": 62,
                "Customer": "Root",
                "Door": "Jail Cells to Evidence Hallway",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 20,
                "OutZoneId": 22
            },
            {
                "Id": 66,
                "Customer": "Root",
                "Door": "Gate Front",
                "ControllerStatus": "Online",
                "LockStatus": "LockedNormal",
                "DoorStatus": "ClosedNormal",
                "BatteryStatus": null,
                "InCameraId": null,
                "OutCameraId": null,
                "InZoneId": 39,
                "OutZoneId": 40
            }
        ]
    }
}